### ISSUE TITLE
documentation issue for Capistrano integration

### ISSUE THREAD

**Issue by jakeonfire** [bugsnag/bugsnag-capistrano#14]
Following the instructions on https://docs.bugsnag.com/api/deploy-tracking/capistrano/ and trying to load the environment results in the error:
```
.../gems/bundler-1.16.0/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'bugsnag-capistrano'.
Gem Load Error is: uninitialized constant Capistrano
Backtrace for gem load error is:
.../gems/bugsnag-capistrano-1.1.1/lib/bugsnag-capistrano/capistrano.rb:3:in `<top (required)>'
.../gems/bugsnag-capistrano-1.1.1/lib/bugsnag-capistrano.rb:2:in `<top (required)>'
```
The Gemfile installation should show:
```
gem 'bugsnag-capistrano', require: false
```
so that only the Capfile tries to load the gem where the environment can provide the Capistrano constant.

**Comment by Kufert** [comment]
@Cawllec please update the docs. could have saved me an hour :/

**Comment by pabuisson** [comment]
Same for me here. Had the same issue, couldn't figure it out until I found this.

**Comment by Cawllec** [comment]
Sorry, we're in the process of updating this gem at the moment.  I'll make sure the docs have the appropriate section updated.
