### ISSUE TITLE
Integration guide possibly incorrect regarding Capfile?

### ISSUE THREAD

**Issue by aimee-ault** [bugsnag/bugsnag-capistrano#18]
Hi! :wave: I wasn't sure where to file this since it's not technically related to the gem's repo itself but I noticed the integration guide recommends adding to your `Capfile`:

```ruby
require "busgnag-capistrano" 
```

This fails for me, throwing an error about not being able to find aforementioned file. If I change it to:

```ruby
require "bugsnag/capistrano"
```

That works like a charm.

I noticed there were a couple of examples in the repo too for both Capistrano 2 and 3 that had the path I mentioned above in the `README` but the included `Capfile` had the first version.

I'm assuming the latter is the correct one, but since I didn't see the integration guide in this repo, I wasn't able to just submit a PR to fix it (and also just wanted to confirm that that was actually correct, anyway!)

**Comment by martin308** [comment]
Hi @aimee-ault, good spot on the inconsistencies in this repo! We can certainly tidy those up.

Are you able to provide any more reproduction details about the error you are getting? (ruby version, bundler version, Capistrano version etc.)

I was able to successfully run both of the examples in this repo with both version `2.0.0` and `1.1.2` of this gem which use the `require 'bugsnag-capistrano'` method.

**Comment by aimee-ault** [comment]
🤦‍♀️ 
@martin308 I ended up figuring out the issue with "bugsnag-capistrano" not working -- we use Docker and I hadn't updated the Gemfile used for determining which gems are needed on the host within our Docker setup to include the bugsnag-capistrano gem as well, so it was legitimately not finding it when attempting to deploy 😄

**Comment by martin308** [comment]
@aimee-ault thanks for letting me know! I'll get those readme require statements fixed up so they don't lead anyone down the wrong path in the future
