### ISSUE TITLE
 No API key found when notifying of deploy

### ISSUE THREAD

**Issue by chrisokamoto** [bugsnag/bugsnag-capistrano#7]
I am getting 

> *** Bugnsag deploy notification failed, #<RuntimeError: No API key found when notifying of deploy>

even when the ENV["BUGSNAG_API_KEY"] is defined..

**Comment by Cawllec** [comment]
Hi @chrisokamoto, are you using bugsnag-capistrano with the main bugsnag-ruby notifier installed, or standalone?

**Comment by chrisokamoto** [comment]
Yes, I am.. when I do `bundle exec cap staging bugsnag:deploy BUGSNAG_API_KEY=ENV['BUGSNAG_API_KEY']` it works, but if I do `bundle exec cap staging bugsnag:deploy` it doesn't work

**Comment by Cawllec** [comment]
It should be pulling if "BUGSNAG_API_KEY" if able.  
What version of capistrano are you using? So I can narrow down the script that's running

**Comment by chrisokamoto** [comment]
capistrano (2.12.0)
bugsnag (6.2.0)
bugsnag-capistrano (1.1.0)

**Comment by Cawllec** [comment]
Hmm, I'm not seeing this behaviour.  Are you setting your `ENV['BUGSNAG_API_KEY']` in your Capfile, or through some config like Rails?

**Comment by chrisokamoto** [comment]
The variable is defined in secrets.yml

**Comment by Cawllec** [comment]
If I understand correctly (please tell me if I'm wrong) you've got your BUGSNAG_API_KEY in secrets.yml, and that configures bugsnag through environment variables?  I'm not certain that Capistrano will pull those variables into the Ruby instance when you run it.

You could try putting something like:
```ruby
set :bugsnag_api_key, Rails.application.secrets.some_api_key
```
to ensure it's getting pulled in properly.

**Comment by boena** [comment]
I'm having the same issue. I've set BUGSNAG_API_KEY in ENV and added the bugsnag-capistrano to the Capfile. As I understand the docs that should be enough? Or do I actually need to specify in the Capfile `set :bugsnag_api_key, ENV['BUGSNAG_API_KEY']`?

Using:
capistrano 3.4.0
bugsnag-capistrano 1.1.1
bugsnag 6.6.3

**Comment by Cawllec** [comment]
@boena yes that should be enough, if `:bugsnag_api_key` isn't set the capfile should fall back on `ENV['BUGSNAG_API_KEY']` as a default

**Comment by boena** [comment]
@Cawllec - Weird. Could it be that I'm using the likes of dotenv/figaro to set ENV variables? Never had a similar problem with that though... @chrisokamoto how are you setting the ENV variable?

**Comment by Cawllec** [comment]
It could be.  A good check would be to log `ENV['BUGSNAG_API_KEY']` from your capfile and see what it says.

**Comment by chrisokamoto** [comment]
I think I just needed to set the BUGSNAG_API_KEY when deploying, once, and then after that it just worked: BUGSNAG_API_KEY=[bugsnag_api_key] bundle exec cap staging deploy
