### ISSUE TITLE
Support multiple bugsnag_api_key

### ISSUE THREAD

**Issue by tiagotex** [bugsnag/bugsnag-capistrano#9]
In our app we use 2 keys in one project to differentiate between JS and Ruby errors.

Until updating to bugsnag-ruby 6 we had a task very similar to the [one in this file](https://github.com/bugsnag/bugsnag-capistrano/blob/master/lib/bugsnag-capistrano/tasks/bugsnag.cap#L25).

We set `bugsnag_api_keys` as an keys array in the Capistrano file instead of the current `bugsnag_api_key`, the rake task creates a deploy notification for each key.

Since I don't think it would be nice to break the current API, we could support both `bugsnag_api_key` and `bugsnag_api_keys`.

I could implement this change if this is something you are interested in having.

**Comment by Cawllec** [comment]
Hi @tiagotex, this sounds like it could be quite useful, if you'd like to submit a PR!  We're planning on doing a release soon, so I'll like at your other PRs as well.

**Comment by boena** [comment]
👍

**Comment by tiagotex** [comment]
Starting to implement this.
